export const Cards=[
  {id:1,name:"Schiacciata mancata in gara",emoji:"😬",indiceSfortuna:4.0},
  {id:2,name:"Scarpa slacciata durante il lay-up",emoji:"👟",indiceSfortuna:7.5},
  {id:3,name:"Fallo tecnico per protesta",emoji:"😤",indiceSfortuna:11.0},
  {id:4,name:"Sbagli il tiro libero decisivo",emoji:"🏀",indiceSfortuna:20.5},
  {id:5,name:"Sbagliano il numero della tua maglia",emoji:"🎽",indiceSfortuna:19.0},
  {id:6,name:"Finisci in panchina per un rookie",emoji:"🪑",indiceSfortuna:22.5},
  {id:7,name:"Scivoli sul parquet in contropiede",emoji:"🪵",indiceSfortuna:45.5},
  {id:8,name:"Il coach ti toglie nei playoff",emoji:"😔",indiceSfortuna:29.5},
  {id:9,name:"Il tuo selfie nello spogliatoio finisce sui giornali",emoji:"🤳",indiceSfortuna:33.0},
  {id:10,name:"Inpanichi durante l'intervista",emoji:"📺",indiceSfortuna:36.0},
  {id:11,name:"Giocatore avversario ti fa ankle-breaker e mette una tripla",emoji:"💀",indiceSfortuna:39.5},
  {id:12,name:"Manchi il draft per un infortunio stupido",emoji:"🤕",indiceSfortuna:43.0},
  {id:13,name:"Vieni chiamato Rookie dell'anno ma vieni scartato dalla tua franchigia",emoji:"💱",indiceSfortuna:46.0},
  {id:14,name:"Sputato da un compagno durante l'esultanza",emoji:"💦",indiceSfortuna:49.5},
  {id:15,name:"La franchigia fa scadere il tuo contratto",emoji:"📝",indiceSfortuna:52.5},
  {id:16,name:"Scambiato il giorno di Natale",emoji:"🎄",indiceSfortuna:55.5},
  {id:17,name:"Perdi scarpa durante partita playoff",emoji:"👟",indiceSfortuna:44.0},
  {id:18,name:"LeBron dice che sei facile da difendere",emoji:"😂",indiceSfortuna:61.0},
  {id:19,name:"Dormi durante il timeout",emoji:"😴",indiceSfortuna:63.5},
  {id:20,name:"Intervistato in diretta e dimentichi il nome del coach",emoji:"🎙️",indiceSfortuna:66.0},
  {id:21,name:"Convocato all'All-Star e poi escluso per infortunio",emoji:"⭐",indiceSfortuna:68.5},
  {id:22,name:"Il tuo contratto con Nike viene annullato",emoji:"📡",indiceSfortuna:71.0},
  {id:23,name:"Infortunio al dito durante il riscaldamento",emoji:"☝️",indiceSfortuna:73.5},
  {id:24,name:"La tua squadra esulta senza di te",emoji:"🏆",indiceSfortuna:76.0},
  {id:25,name:"Eliminato al primo turno da una 8a testa di serie",emoji:"😱",indiceSfortuna:78.0},
  {id:26,name:"Il tuo allenatore ti accusa pubblicamente",emoji:"🗣️",indiceSfortuna:80.0},
  {id:27,name:"Perdi le Finals per un rimbalzo offensivo",emoji:"😭",indiceSfortuna:82.0},
  {id:28,name:"Bannato dalla NBA per 10 partite",emoji:"🚫",indiceSfortuna:83.5},
  {id:29,name:"Infortunio al ginocchio che finisce la carriera",emoji:"🦵",indiceSfortuna:85.5},
  {id:30,name:"Il video di te che piangi diventa virale",emoji:"😢",indiceSfortuna:87.0},
  {id:31,name:"Bannato permanentemente dalla NBA per tatuaggio non ammesso",emoji:"✒️",indiceSfortuna:88.5},
  {id:32,name:"La tua franchigia viene trasferita",emoji:"🚚",indiceSfortuna:89.5},
  {id:33,name:"Escluso dalla Hall of Fame per anni",emoji:"🏛️",indiceSfortuna:90.5},
  {id:34,name:"Tagliato 48 ore prima dell'inizio stagione",emoji:"✂️",indiceSfortuna:91.5},
  {id:35,name:"Doping positivo per uso inconsapevole",emoji:"💊",indiceSfortuna:92.5},
  {id:36,name:"La tua miglior stagione cancellata dal lockout",emoji:"🔒",indiceSfortuna:93.5},
  {id:37,name:"Il tuo migliore amico firma con la squadra rivale",emoji:"😤",indiceSfortuna:94.0},
  {id:38,name:"Infortunio alle Olimpiadi e perdi la medaglia d'oro",emoji:"🥇",indiceSfortuna:94.5},
  {id:39,name:"Ritirato per infortuni ripetuti a 28 anni",emoji:"👋",indiceSfortuna:95.0},
  {id:40,name:"Ja Morant ti schiaccia in post",emoji:"🐻",indiceSfortuna:62.5},
  {id:41,name:"Il tuo numero ritirato e poi ridato ad altri",emoji:"🔢",indiceSfortuna:51.0},
  {id:42,name:"Fischiato dai tuoi tifosi in casa",emoji:"👎",indiceSfortuna:50.0},
  {id:43,name:"Un ala piccola ti schiaccia in testa",emoji:"🤯",indiceSfortuna:45.0},
  {id:44,name:"Pubblichi per errore il numero del tuo coach",emoji:"☎️",indiceSfortuna:30.5},
  {id:45,name:"Escluso dalla lista dei 75 migliori NBA",emoji:"📋",indiceSfortuna:69.5},
  {id:46,name:"Caduta in riscaldamento",emoji:"🤸",indiceSfortuna:13.5},
  {id:47,name:"Ankle-breaker in finale al buzzer che vi porta alla sconfitta",emoji:"🦵",indiceSfortuna:98.0},
  {id:48,name:"Scambiato mentre sei in vacanza",emoji:"🏖️",indiceSfortuna:57.0},
  {id:49,name:"ESPN ti chiama sopravvalutato dell'anno",emoji:"📰",indiceSfortuna:37.5},
  {id:50,name:"Tripla doppia record ma perdi di 20 punti",emoji:"📊",indiceSfortuna:9.0},
];
export const getRandomCards=(count,excludeIds=[])=>{
  const available=Cards.filter((c)=>!excludeIds.includes(c.id));
  const shuffled=[...available].sort(()=>Math.random()-0.5);
  return shuffled.slice(0,count);
};